import './globals.css'


export const metadata = {
  title: 'Murad Hossain Sarker',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          This is header
        </header>
        {children}
        <footer>
          This is footer
        </footer>
        </body>
    </html>
  )
}
